name: CI-CD Unreal Engine Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      logs: ${{ steps.capture.outputs.logs }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Intentional error
        run: |
          some_command_that_does_not_exist

      - name: Call CI Smart Agent
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.AGENT_GITHUB_TOKEN }}
        run: |
          LOGS=$(cat $GITHUB_WORKSPACE/**/*.log 2>/dev/null | jq -Rs . || echo "\"Build failed\"")
      
          curl -X POST https://api.github.com/repos/vyaspurva20/ci-bot-agent/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -d "{
              \"event_type\": \"fix_project_repo\",
              \"client_payload\": {
                \"logs\": $LOGS
              }
            }"


          
        
            
